# Generated by Django 2.1.2 on 2018-11-10 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Person', '0001_initial'),
        ('Order_dinner', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elaluate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goodsScore', models.IntegerField()),
                ('serviceScore', models.IntegerField()),
                ('content', models.CharField(max_length=120)),
                ('image', models.ImageField(upload_to='')),
                ('isshow', models.BooleanField()),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order.Order')),
                ('shopid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order_dinner.Seller')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Person.Customer')),
            ],
        ),
    ]
