# Generated by Django 2.1.2 on 2018-11-11 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elaluate',
            name='orderid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.Order'),
        ),
        migrations.AlterField(
            model_name='elaluate',
            name='shopid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_dinner.Seller'),
        ),
        migrations.AlterField(
            model_name='elaluate',
            name='userid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.Customer'),
        ),
    ]
