# Generated by Django 2.1.3 on 2018-11-13 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puantity', models.IntegerField(default=0)),
                ('state', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=30)),
                ('msq', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(null=True)),
                ('describe', models.CharField(max_length=300)),
                ('photo', models.CharField(default='wm-1.gif', max_length=100)),
                ('food_type', models.CharField(default='木桶饭', max_length=100)),
                ('Commodity_type', models.CharField(default='早餐/汉堡', max_length=50)),
            ],
            options={
                'db_table': 'Food',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('starting_price', models.IntegerField()),
                ('dist_price', models.IntegerField()),
                ('Monthle_sale', models.IntegerField(default='30')),
                ('reduce', models.IntegerField(default='13')),
                ('price_reduction', models.IntegerField(default='13')),
                ('new_price', models.IntegerField(default='18')),
                ('pictur', models.CharField(default='wm-1.gif', max_length=100)),
                ('Sphone', models.BigIntegerField()),
                ('Business_hours', models.CharField(default='8:00-21:00', max_length=100)),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order_dinner.Seller'),
        ),
        migrations.AddField(
            model_name='cart',
            name='Food',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='Order_dinner.Food'),
        ),
    ]
