# Generated by Django 2.1.2 on 2018-11-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fname', models.CharField(max_length=20)),
                ('msq', models.IntegerField()),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(null=True)),
                ('describe', models.CharField(max_length=200)),
                ('food_photo', models.ImageField(height_field=500, upload_to='img', width_field=500)),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('starting_price', models.IntegerField()),
                ('dist_price', models.IntegerField()),
                ('seller_photo', models.ImageField(height_field=500, upload_to='img', width_field=500)),
                ('Sphone', models.IntegerField()),
            ],
            options={
                'db_table': 'Seller',
            },
        ),
        migrations.AddField(
            model_name='food',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order_dinner.Seller'),
        ),
    ]
