# Generated by Django 2.1.2 on 2018-11-14 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('Order_dinner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Person.Customer'),
        ),
    ]
