# Generated by Django 2.1.2 on 2018-11-10 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Sphone',
            field=models.IntegerField(max_length=23),
        ),
    ]
