# Generated by Django 2.1.2 on 2018-11-10 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0002_auto_20181110_0736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='Sphone',
            field=models.BigIntegerField(),
        ),
    ]
