# Generated by Django 2.1.2 on 2018-11-14 07:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0002_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Order_dinner.Seller'),
        ),
    ]
