# Generated by Django 2.1.2 on 2018-11-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0003_auto_20181110_0747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='seller_photo',
        ),
        migrations.AlterModelTable(
            name='food',
            table='Food',
        ),
    ]
