# Generated by Django 2.1.2 on 2018-11-10 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0004_auto_20181110_0803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_photo',
        ),
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.CharField(default='wm-1.gif', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='Monthle_sale',
            field=models.IntegerField(default='13'),
        ),
        migrations.AddField(
            model_name='seller',
            name='new_price',
            field=models.IntegerField(default='13'),
        ),
        migrations.AddField(
            model_name='seller',
            name='pictur',
            field=models.CharField(default='wm-1.gif', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='price_reduction',
            field=models.IntegerField(default='13'),
        ),
        migrations.AddField(
            model_name='seller',
            name='reduce',
            field=models.IntegerField(default='13'),
        ),
        migrations.AlterField(
            model_name='food',
            name='Fname',
            field=models.CharField(default='黄焖米饭', max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='Seller',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.DO_NOTHING, to='Order_dinner.Seller'),
        ),
        migrations.AlterField(
            model_name='food',
            name='describe',
            field=models.CharField(default='黄焖米饭', max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='food',
            name='msq',
            field=models.IntegerField(default='1'),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(default='1'),
        ),
    ]
