# Generated by Django 2.1.2 on 2018-11-10 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0005_auto_20181110_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='Fname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='food',
            name='Seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Order_dinner.Seller'),
        ),
        migrations.AlterField(
            model_name='food',
            name='describe',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='food',
            name='discount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='msq',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='food',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='seller',
            name='Monthle_sale',
            field=models.IntegerField(default='30'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='new_price',
            field=models.IntegerField(default='18'),
        ),
    ]
