# Generated by Django 2.1.2 on 2018-11-11 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0006_auto_20181110_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='food_type',
            field=models.CharField(default='早餐/汉堡', max_length=100),
        ),
        migrations.AddField(
            model_name='seller',
            name='Business_hours',
            field=models.CharField(default='8:00-21:00', max_length=100),
        ),
    ]
