# Generated by Django 2.1.2 on 2018-11-11 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0007_auto_20181111_0113'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='Commodity_type',
            field=models.CharField(default='早餐/汉堡', max_length=50),
        ),
        migrations.AlterField(
            model_name='food',
            name='food_type',
            field=models.CharField(default='木桶饭', max_length=100),
        ),
    ]
