# Generated by Django 2.1.2 on 2018-11-12 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order_dinner', '0009_cart'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='Cart',
        ),
    ]
