# Generated by Django 2.1.2 on 2018-11-17 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=100)),
                ('Aphone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=20)),
                ('pay_password', models.IntegerField()),
                ('loyalty', models.IntegerField()),
                ('vips', models.IntegerField()),
                ('head', models.ImageField(upload_to='')),
                ('ex_password', models.IntegerField()),
                ('wallet', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('wechat', models.CharField(max_length=20)),
                ('qq', models.IntegerField()),
                ('add_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='uid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Person.Customer'),
        ),
    ]
