# Generated by Django 2.1.2 on 2018-11-10 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_detail_number', models.IntegerField()),
                ('order_detail_money', models.IntegerField()),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.IntegerField(choices=[(0, '未发送'), (1, '已发送'), (2, '确认收货')])),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.IntegerField()),
                ('order_money', models.IntegerField()),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.IntegerField(choices=[(0, '未发送'), (1, '已发送'), (2, '确认收货')])),
                ('history_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.History')),
            ],
        ),
        migrations.CreateModel(
            name='Order_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_detail_number', models.IntegerField()),
                ('order_detail_money', models.IntegerField()),
                ('order_num', models.IntegerField()),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('order_detail_remarks', models.CharField(max_length=40)),
                ('history_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.History')),
                ('order_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.Order')),
            ],
        ),
        migrations.AddField(
            model_name='history',
            name='order_detail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.Order_detail'),
        ),
        migrations.AddField(
            model_name='history',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order.Order'),
        ),
    ]
