# Generated by Django 2.1.2 on 2018-11-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Person', '0001_initial'),
        ('Order_dinner', '0001_initial'),
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.Address'),
        ),
        migrations.AddField(
            model_name='history',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.Customer'),
        ),
        migrations.AddField(
            model_name='history',
            name='food_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_dinner.Food'),
        ),
        migrations.AddField(
            model_name='history',
            name='seller_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_dinner.Seller'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.Customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='food_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_dinner.Food'),
        ),
        migrations.AddField(
            model_name='order',
            name='seller_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_dinner.Seller'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='address_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.Address'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='customer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Person.Customer'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='food_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_dinner.Food'),
        ),
        migrations.AddField(
            model_name='order_detail',
            name='seller_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Order_dinner.Seller'),
        ),
    ]
