# Generated by Django 2.1.2 on 2018-11-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20181118_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_money',
            field=models.IntegerField(null=True),
        ),
    ]
