# Generated by Django 2.1.2 on 2018-11-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_auto_20181118_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '未发送'), (1, '已发送'), (2, '确认收货')], null=True),
        ),
    ]
